#!/bin/bash

referer=""
GETELEMFUNC="wget"
QQEDIR="~/.fetch4me"

if [ -e ~/.fetch4merc ]
then
	s=`cat ~/.fetch4merc | grep QQEDIR=`
	if [ "$s" != "" ]
	then
		QQEDIR=${s:7}
		echo "QQEDIR readed from file ~/.fetch4merc. Now it's value is \"$QQEDIR\""
	fi

	s=`cat ~/.fetch4merc | grep GETELEMFUNC=`
        if [ "$s" != "" ]
        then
                GETELEMFUNC=${s:12}
                echo "GETELEMFUNC readed from file ~/.fetch4merc. Now it's value is \"$GETELEMFUNC\""
        fi
fi

function changeReferer() {
	referer=$1
#	echo "referer changed to $referer"
}

function changeDir() {
	QQEDIR=$1
#	echo "QQEDIR changed to $QQEDIR"
}

function start4me() {
	echo $@
}

while getopts ":r:w:" opt; do
	case $opt in
		r)
			if [ "$((OPTIND-1))" -eq "$#" ]
			then
				echo "It should be at least one URL (because -r used)"
			fi
			changeReferer $OPTARG
		;;

		w)
			changeDir $OPTARG
		;;

		:)
			echo "Argument required -$OPTARG"
			exit 1
		;;

		*)
			echo "Unknown arg -$OPTARG"
			exit 1
		;;
	esac
done

shift $((OPTIND-1))
start4me $@
