#!/bin/bash -e

#default options
config=~/.fetch4merc
referer=""
GETELEMFUNC="wget -c"
QQEDIR=~/.fetch4me
download_dir=~/Downloads/fetched4you/
source $config
declare -a urls

function awrite() {
	local args=($@)
	local dir=$1
	local file=$(getNormalName $2)
	touch $dir/$file.temp
	for (( c=2; c < $#; c++ ))
	do
		echo ${args[$c]} >> $dir/$file.temp
	done
	mv $dir/$file.temp $dir/$file
}

function changeReferer() {
	referer=$1
#	echo "referer changed to $referer"
}

function changeDir() {
	QQEDIR=$1
#	echo "QQEDIR changed to $QQEDIR"
}

function getNormalName() {
	local tempurl=$1
	tempurl=${tempurl//\//%2F}
	echo $tempurl
}

function addTask() {
	if [ -z $referer ]
	then
		awrite $QQEDIR $1.task " $1" "$1" "none"
	else
		awrite $QQEDIR $referer$1.task " --referer $referer $1" "$1" "$referer"
	fi
}

function start4me() {
	if [ ! -e $QQEDIR/.pid ]
	then
		echo -1 > $QQEDIR/.pid
	fi

	exec < $QQEDIR/.pid
	read pid
	t=`ps axu | grep "^[a-zA-Z0-9]*[ ]*$pid"` || true
	if [ -z "$t" ]
	then
		(trap '' HUP; exec ./fetch4me)&
		echo $! > "$QQEDIR/.pid"
		exit
	fi
	
	if [ $$ != "$pid" ]
	then
		if [ $# -eq 0 ]
		then
			echo "At least one arg required"
			exit 1
		fi
		exit
	fi
	
	awrite $QQEDIR .pid $$
}

if [ ! -d $download_dir ]
then
	mkdir -p $download_dir
fi

while getopts ":r:w:" opt
do
	case $opt in
		r)
			if [ "$((OPTIND-1))" -eq "$#" ]
			then
				echo "It should be at least one URL (because -r used)"
			fi
			changeReferer $OPTARG
		;;

		w)
			changeDir $OPTARG
		;;

		:)
			echo "Argument required -$OPTARG"
			exit 1
		;;

		*)
			echo "Unknown arg -$OPTARG"
			exit 1
		;;
	esac
done

args=("$@")
c=0
OPTIND=$((OPTIND-1))
while [ $OPTIND -lt $# ]
do
	urls[$c]=${args[$OPTIND]}
	c=$((c+1))
	OPTIND=$((OPTIND+1))
done

if [ ! -e $QQEDIR ]
then
	mkdir $QQEDIR
fi

for u in ${urls[@]}
do
	addTask $u
done

start4me $@

cd $QQEDIR

if [ ! -e ".finished" ]
then
	touch .finished
fi

if [ ! -e ".queue" ]
then
	touch .queue
fi

for (( ; ; ))
do
	declare -a queue
done
